version: '3'

services:
  rabbitmq:
    container_name: rabbitmq-container
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 5s
      timeout: 5s
      retries: 5


  offers-service:
    container_name: offers-service-container
    build: ./offers-service
    ports:
      - "8081:8081"
    image: offers-service
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_started
      
  transactions-service:
    container_name: transactions-service-container
    build: ./transactions-service
    ports:
      - "8082:8082"
    image: transactions-service
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_started


