---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "cars-eu-namespace"
---
apiVersion: v1
kind: Secret
metadata:
  name: cars-eu-offers-service-secrets
  namespace: "cars-eu-namespace"
type: Opaque
data:
  HOST: IjM0LjkxLjU0Ljg5Ig==
  PORT: ODA4MQ==
  DB_URI: Im1vbmdvZGIrc3J2Oi8vdXNlck9mZmVyczo4WjZHYmlieE9tWjlLc3VhQGNhcnMtZXUuc3hwem52My5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5Ig==
  DB_NAME: Im9mZmVycy1kYXRhIg==
  DB_COLL_NAME: Im9mZmVycyI=
  MB_URI: ImFtcXBzOi8vb2J5cWRtbHI6NWdUSExNV1ZhSXA3ZGk2WnpsQXRoWkl5UnFGZjZLYkFAa2FuZ2Fyb28ucm1xLmNsb3VkYW1xcC5jb20vb2J5cWRtbHIi
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "cars-eu-offers-service-deployment-config-jhrq"
  namespace: "cars-eu-namespace"
  labels:
    app: "cars-eu-offers-service-deployment"
data:
  NODE_ENV: "prod"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cars-eu-offers-service-deployment"
  namespace: "cars-eu-namespace"
  labels:
    app: "cars-eu-offers-service-deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "cars-eu-offers-service-deployment"
  template:
    metadata:
      labels:
        app: "cars-eu-offers-service-deployment"
    spec:
      containers:
        - name: "offers-service-sha256-1"
          image: "europe-west4-docker.pkg.dev/cars-eu/cars-eu/offers-service:latest"
          env:
            - name: "NODE_ENV"
              valueFrom:
                configMapKeyRef:
                  key: "NODE_ENV"
                  name: "cars-eu-offers-service-deployment-config-jhrq"
            - name: "HOST"
              valueFrom:
                secretKeyRef:
                  key: "HOST"
                  name: "cars-eu-offers-service-secrets"
            - name: "PORT"
              valueFrom:
                secretKeyRef:
                  key: "PORT"
                  name: "cars-eu-offers-service-secrets"
            - name: "DB_URI"
              valueFrom:
                secretKeyRef:
                  key: "DB_URI"
                  name: "cars-eu-offers-service-secrets"
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  key: "DB_NAME"
                  name: "cars-eu-offers-service-secrets"
            - name: "DB_COLL_NAME"
              valueFrom:
                secretKeyRef:
                  key: "DB_COLL_NAME"
                  name: "cars-eu-offers-service-secrets"
            - name: "MB_URI"
              valueFrom:
                secretKeyRef:
                  key: "MB_URI"
                  name: "cars-eu-offers-service-secrets"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "cars-eu-offers-service-deployment-hpa-fk06"
  namespace: "cars-eu-namespace"
  labels:
    app: "cars-eu-offers-service-deployment"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "cars-eu-offers-service-deployment"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "cars-eu-offers-service-deployment-service"
  namespace: "cars-eu-namespace"
  labels:
    app: "cars-eu-offers-service-deployment"
spec:
  ports:
    - protocol: "TCP"
      port: 8081
  selector:
    app: "cars-eu-offers-service-deployment"
  type: "LoadBalancer"
  loadBalancerIP: 34.147.123.91
