name: Docker Image CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    variables:
      NODE_ENV: dev
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variables
        env:
          NODE_ENV: dev
        run: docker-compose up
      # - name: Start the Docker containers
      #   run: docker-compose up
      - name: Stop and remove Docker containers
        run: docker-compose down
