name: Docker Image CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set env vars
        run: echo "NODE_ENV=dev"
      - name: Build the solution
        run: docker-compose build
      - name: Start the Docker containers
        run: docker-compose up
      - name: Stop and remove Docker containers
        run: docker-compose down
