name: Deploy Offers service to Google Kubernetes Engine

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: cars-eu
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker + apply Kubernetes
        run: |
          cd offers-service
          gcloud auth configure-docker europe-west4-docker.pkg.dev
          docker build -t europe-west4-docker.pkg.dev/cars-eu/cars-eu/offers-service:latest -f Dockerfile .
          docker push europe-west4-docker.pkg.dev/cars-eu/cars-eu/offers-service:latest
          gcloud components install kubectl
          gcloud container --project "cars-eu" clusters create-auto "cars-eu-offers-service" --region "europe-west4" --release-channel "regular" --network "projects/cars-eu/global/networks/default" --subnetwork "projects/cars-eu/regions/europe-west4/subnetworks/default" --cluster-ipv4-cidr "/17" --services-ipv4-cidr "/22"
          gcloud container clusters get-credentials cars-eu-offers-service --zone europe-west4
          cd ../kubernetes
          kubectl apply -f offers-service-config.yml
