name: Deploy Offers service to Google Kubernetes Engine

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: cars-eu
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker + apply Kubernetes
        run: |
          cd offers-service
          gcloud auth configure-docker eu.gcr.io
          docker build -t eu.gcr.io/cars-eu/offers-service@sha256:5ac64e403352cdf375629711b93665fe33ae772ffb196c810d9863e867884fa6:latest -f Dockerfile .
          docker push eu.gcr.io/cars-eu/offers-service@sha256:5ac64e403352cdf375629711b93665fe33ae772ffb196c810d9863e867884fa6:latest 
          gcloud components install kubectl
          gcloud container --project "cars-eu" clusters get-credentials cars-eu-cluster --zone europe-west4
          cd ../kubernetes
          kubectl apply -f offers-service-config.yml
